language: go

# Be explicit about not needing sudo, so that Travis will use container-based
# infrastructure for our jobs, always, fewer heuristics.
sudo: false

matrix:
  allow_failures:
    - go: tip
  fast_finish: true
  include:
    - go: 1.10.x
      env: UPLOAD_COVERAGE=true
    - go: 1.9.x
    - go: tip

branches:
  except:
    - /^(?:exp|wip)(?:[/_-].*)?$/

go_import_path: go.pennock.tech/tabular

# The "correct"ish way is:
# rem="$(git remote)"; old_remote="$(git remote get-url "$rem")"; git remote set-url "$rem" "${old_remote%.git}"
# but Travis's git doesn't recognize the `get-url` sub-command.
# So we use `git config` instead.

install:
  - git --version
  - git config --get remote.origin.url
  - go get -t -v -u ./...
  - test "${UPLOAD_COVERAGE:-false}" != "true" || go get github.com/mattn/goveralls
  - test "${UPLOAD_COVERAGE:-false}" != "true" || go get github.com/wadey/gocovmerge

script:
  - go vet ./...
  - go test -v ./...
  - test "${UPLOAD_COVERAGE:-false}" != "true" || ./CoverTest.sh

# Since I first set up goveralls for other stuff, coveralls.io have added
# Travis integration such that a token is not needed for a public repo.  Neat.
after_script:
  - test "${UPLOAD_COVERAGE:-false}" != "true" || goveralls -coverprofile=coverage.out -service=travis-ci

notifications:
  slack:
    on_success: always
    rooms:
      secure: "iM03Rn3Y6xHfoaOUnmk+LQXI1EWKS6pqht/Tz0+MTNVfuWuaZTKTRpKMFLXp0iz/WgDlbF3cF/3eGEdk4DSclKp8QLvtmtHLjHmt1GT7TrEoS46OkL/YC3SbKpas5zPgwoi/DQragMS/7/Z200ppdL5qiO56v7MNMdcCQTuXt+hPdRUWwxlsRf1qlVzcfFyZ1x2OO/GjKlDCSnYaSsU3Rts+zAdg7JWWhh0jVQ790DmDx/OsiIhD4SUPtUTEla854aRqe0I0FT4jF6YLnlsBMuzL2REhmSUjZVMzfEiYeUSYWHixK2mzNqqgD+LHId2pkHFZ7mzcokDn4oaVt4cxocjNn7/zM4DQSym0HmBdoZw/TxtcvlSfH1DZQJBhsS9nVjMscvQdokZ6MEuurUY+U9kfcg2cB2esR1yr8z5Z7QRBJdQMRVnN91we7O+06c0rS7aR9KGMhKqKOi4O4PxzsWZCwoxDBqPz3wvQD3fullt8gElCvljGqJLz6uZylgmJYikGVq5vXT187BIqvVJvHjLWQQMgsVD+MGPPMqy2k3BgDRsG7yTybkM1Dhiuqbc5Ct8p+VrmY5zpINvDDoZ71dOYf/Ptb1d+juPQeVi8oi+nuLfpif6RXooSZr34ja0atm0KyU+3jnWXpI7Vs4YUomF/Y97Vcfw4SxvgsxX17nU="

# vim: set sw=2 et :
